apiVersion: v2
name: onecx-document-management-ui
version: 999-SNAPSHOT
appVersion: 999-SNAPSHOT
description: onecx document management ui
keywords:
  - angular
  - onecx
sources:
  - https://github.com/onecx-apps/onecx-document-management-ui
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts  
  - name: helm-product
    version: ^0
    repository: oci://ghcr.io/onecx/charts
    alias: product